version: '3.0'

services:
  node:
    depends_on:
      - postgres
    image: my-http
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
    command: npm run start
    networks:
      - custom_network
  postgres:
    restart: always
    image: postgres:14-alpine
    command: "-c logging_collector=on"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql/
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      custom_network:
        aliases:
          - postgresForMyApp

networks:
  custom_network:
    name: custom_network
    driver: bridge

volumes:
  database_data:
    driver: local
  postgres_logs: {}